Add Project Content Type
pacifica/pacifica-drupal-module-content pull request #10
Opened 2019-06-14 05:19 UTC by dmlb2000

### Description

This adds the project content type and tries to create it and read
it back out of the DB.

Signed-off-by: David Brown <dmlb2000@gmail.com>

### Issues Resolved

Fix #3 
### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2019-06-14 21:23 UTC, dmlb2000 reviewed
This looks good overall, please make some naming changes and it will be acceptable.

2019-06-14 21:23 UTC, dmlb2000 commented on pacifica_search/tests/src/Functional/PacificaSearchTest.php
> +  public function testPacificaSearchContentTypeOrg() {
This is a bad name for a test function, you suck!

2019-06-14 21:23 UTC, dmlb2000 commented on pacifica_search/tests/src/Functional/PacificaSearchTest.php
> +  public function testPacificaSearchContentTypeProj() {
This needs to be shorter and less complicated.

2019-06-14 21:23 UTC, dmlb2000 commented on pacifica_search/tests/src/Functional/PacificaSearchTest.php
> +  public function testPacificaSearchVocabTerm() {
Ditto! See Above!

2019-06-14 21:26 UTC, BenjaminStuermer requested changes
A remarkable accomplishment, but still not up to my standards.

2019-06-14 21:27 UTC, BenjaminStuermer approved these changes

2019-06-19 14:13 UTC, dmlb2000 commented
I'm not sure this is a valid fix for the issue. These kind of content types should be configurable after install of the site to be whatever the installer wants them to be. So I think they should be managed by the install profile.

2019-06-19 14:13 UTC, closed without merging

2019-06-19 16:55 UTC, AmericanUmlaut commented
@dmlb2000 I don't understand either of the assertions you're making in your close comment. What is the purpose of having our application create content types that are intended to be arbitrarily reconstructed by the user? If they need content types that are substantially different than what we provide, they can obviously change them, but that would presumably be the work of a dependent module. And I don't see any connection between that and putting content type definitions in an installation profile instead of a module, which doesn't make any sense to me as a concept. Putting a content type in an install profile or a module does the same thing - the .yml file is parsed and the corresponding content type is created at install time. Regardless of the source of that content type, an admin on that site has the power to modify the resulting content type as they choose.

Further, I'm not certain what the sense is of creating new functionality for the creation of the Project content type. I assumed when I first saw this PR that there must be a good reason we can't use the Project content type that James Marks has already authored with whatever modifications are required to support our use cases, but as far as I know we haven't discussed any shortcomings of the existing functionality. Why not iterate on the working solution we already have?

2019-06-19 20:59 UTC, wats958 commented
There are aspects of entities that can be initialized with an install profile and left user-configurable, but we should still be creating entities & fields that we know we want/need for Pacifica's functionality in a module (or site config or distribution). 

If the API, Cart, or any other Pacifica functionality relies on the presence/settings of a certain content type, taxonomy, or field, that should not be in an install profile.